#ifndef PARSER_ERRORS_H
#define PARSER_ERRORS_H

typedef enum
{
    PARSER_OK = 0,
    PARSER_ERR_FILE_OPEN = 1,
    PARSER_ERR_EXPECTED_CONFIG = 2,
    PARSER_ERR_VERSION = 3,
    PARSER_ERR_LINE_TOO_LONG = 4,
    PARSER_ERR_DUPLICATE_ID = 5,
    PARSER_ERR_MISSING_REQUIRED = 6,
    PARSER_ERR_INVALID_REFERENCE = 7,
    PARSER_ERR_INVALID_WIRING = 8,
    PARSER_ERR_INVALID_NOTCH = 9,
    PARSER_ERR_INVALID_FORMAT = 10,
    PARSER_ERR_INTERNAL = 127
} ParserErrorCode;

#endif
